<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\User_SAML\Support;

use OCA\User_SAML\SAMLSettings;
use OCP\IL10N;
use OCP\SystemReport\ISystemReportSection;
use OCP\SystemReport\SystemReportDetail;
use OCP\SystemReport\SystemReportDetailFormat;

/**
 * Contributes the configuration of every configured SAML provider to the
 * system report generated by the support app.
 */
class SystemReportSection implements ISystemReportSection {
	/**
	 * Keys from SAMLSettings::IDP_CONFIG_KEYS that must never end up in a
	 * system report, since it is commonly shared with third parties.
	 */
	private const SECRET_KEYS = [
		'sp-privateKey',
	];

	/**
	 * Certificates are not secret, but reporting them in full only adds
	 * noise, so only whether one is configured is reported.
	 */
	private const PRESENCE_ONLY_KEYS = [
		'idp-x509cert',
		'sp-x509cert',
	];

	public function __construct(
		private readonly SAMLSettings $samlSettings,
		private readonly IL10N $l10n,
	) {
	}

	#[\Override]
	public function getId(): string {
		return 'saml';
	}

	#[\Override]
	public function getTitle(): string {
		return $this->l10n->t('SAML');
	}

	#[\Override]
	public function getDetails(): array {
		$details = [];

		foreach ($this->samlSettings->getListOfIdps() as $id => $displayName) {
			$title = $displayName !== '' ? $displayName : $this->l10n->t('SAML provider #%s', [(string)$id]);
			$details[] = new SystemReportDetail(
				$title,
				$this->renderConfig($this->samlSettings->get((int)$id)),
				SystemReportDetailFormat::Preformatted,
			);
		}

		return $details;
	}

	private function renderConfig(array $config): string {
		$lines = [];
		foreach (SAMLSettings::IDP_CONFIG_KEYS as $key) {
			if (in_array($key, self::SECRET_KEYS, true)) {
				continue;
			}

			$value = $config[$key] ?? '';
			if (in_array($key, self::PRESENCE_ONLY_KEYS, true)) {
				$value = $value !== '' ? 'configured' : 'not configured';
			} elseif (is_array($value)) {
				$value = implode(';', $value);
			}

			$lines[] = $key . ': ' . $value;
		}

		return implode("\n", $lines);
	}
}
